### ISSUE TITLE
(7.x.x) - Roadmap for typescript support

### ISSUE THREAD

**Issue by swingingtom** [felixmariotto/three-mesh-ui#204]
The [branch 7.x.x](https://github.com/felixmariotto/three-mesh-ui/tree/7.x.x)  wants to be __typescript friendly__.

Please comment this thread if you find some typescript issues (on the 7.x.x branch). Issues will be added to this roadmap.
Some work is already done, but it now requires typescript users to finalize it compatibility.

### Roadmap
- [x] use jsDoc to generate types.d ( @JoeCoppola-HIA thanks ! )
    - [x] fix missing jsDoc import with appropriate comment imports
- [ ] Outstanding issues from #192 
    - [x] Remove mixins
    - [ ] Find why/ how to prevent `EventDispatcher` to become `EventDispatcher<Event>` during ts generation
- [ ] #190 in order to monitor types updates and regressions
